[package]
name = "eeos"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "eeos"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
numpy = "0.24"

reeos= {path=".."}