[package]
name = "reeos"
version = "0.1.0"
edition = "2021"

[lib]
name = "reeos"


[dependencies] 
nalgebra = "0.33.2"
serde = { version = "1.0.217", features = ["derive"] }
ndarray ="0.16.1"
serde_json = "1.0"
thiserror = "2"
approx = "0.5"
